name: 'cleanup'
description: 'cleanup canary'
inputs:
  type:
    description: 'type'
    required: false
    default: 'add'
  conclusion:
    description: 'conclusion'
    required: false
    default: 'success'
runs:
  using: 'node12'
  main: 'lib/index.js'
