name: 'build'
on:
  workflow_run:
    workflows:
      - test
    branches:
      - master
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          always-auth: true
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@karakuri-ai'
          token: ${{ secrets.GPR_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build
      # - run: |
      - run: tar -cvf build.tar action.yml lib cleanup
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar
  release:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: |
          tar -xvf build.tar
          rm -f build.tar
      - run: |
          git config --global user.email "push@no-reply.github.com"
          git config --global user.name "GitHub Push Action"

          if [ -z "$(git status --porcelain)" ]; then
            echo "Clean!"
          else
            git add --all

            git status
            git commit -m "GitHub Push"
            git push origin $BRANCH
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          BRANCH: master
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 'marvinpinto/action-automatic-releases@v1.1.1'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: false
