name: 'build'
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          always-auth: true
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@karakuri-ai'
          token: ${{ secrets.GPR_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build
      # - run: |
